Reimplement serial device using epoll and eventfd
sysprog21/kvm-host pull request #16
Opened 2023-06-13 05:59 UTC by yanjiew1

After this change, the I/O handler called during VM exit will only need to deal with the FIFO buffers on the device. The work to interact with the terminal is offloaded to the worker thread.

The main thread use eventfd to signal the worker thread. The worker thread uses epoll to monitor stdin, stdout and the eventfd and will be notified when the state of one of these file descriptors change and perform the I/O when necessary.

Besides changing the original implementation to use eventfd and epoll, I also make the emulated device hehave more like a physical device. The notable change is that the loopback mode is implemented.

2023-06-13 06:05 UTC, jserv requested changes
Improve the git commit messages by fixing some mistakes.

2023-06-13 06:17 UTC, jserv commented
gcc-9 complains as the following:
```
src/serial.c: In function ‘serial_in’:
src/serial.c:327:9: error: a label can only be part of a statement and a declaration is not a statement
  327 |         uint8_t iir = __atomic_load_n(&priv->iir, __ATOMIC_ACQUIRE);
      |         ^~~~~~~
src/serial.c:345:9: error: a label can only be part of a statement and a declaration is not a statement
  345 |         uint8_t lsr = __atomic_load_n(&priv->lsr, __ATOMIC_RELAXED);
      |         ^~~~~~~
```

Quick fix:
```diff
--- a/src/serial.c
+++ b/src/serial.c
@@ -323,7 +323,7 @@ static void serial_in(serial_dev_t *s, uint16_t offset, void *data)
         else
             IO_WRITE8(data, priv->ier);
         break;
-    case UART_IIR:
+    case UART_IIR: {
         uint8_t iir = __atomic_load_n(&priv->iir, __ATOMIC_ACQUIRE);
         IO_WRITE8(data, iir);
         if ((iir & UART_IIR_ID) == UART_IIR_THRI) {
@@ -335,13 +335,14 @@ static void serial_in(serial_dev_t *s, uint16_t offset, void *data)
             pthread_mutex_unlock(&priv->lock);
         }
         break;
+    }
     case UART_LCR:
         IO_WRITE8(data, priv->lcr);
         break;
     case UART_MCR:
         IO_WRITE8(data, priv->mcr);
         break;
-    case UART_LSR:
+    case UART_LSR: {
         uint8_t lsr = __atomic_load_n(&priv->lsr, __ATOMIC_RELAXED);
         IO_WRITE8(data, lsr);
         if (lsr & UART_LSR_BRK_ERROR_BITS) {
@@ -352,6 +353,7 @@ static void serial_in(serial_dev_t *s, uint16_t offset, void *data)
             pthread_mutex_unlock(&priv->lock);
         }
         break;
+    }
     case UART_MSR:
         IO_WRITE8(data, priv->msr);
         if (priv->msr & UART_MSR_ANY_DELTA) {
```

2023-06-13 06:20 UTC, jserv commented on src/utils.h
> +#pragma once
Don't do that. Minimize the necessary changes.

2023-06-14 11:48 UTC, RinHizakura commented on src/serial.c
> +    bool initialized;
What's the variable used for? When will we reinitialize the serial device incorrectly?

2023-06-14 11:48 UTC, RinHizakura commented on src/serial.c
> +    evfd = infd = outfd = epollfd = -1;
I don't think closing a file descriptor with a negative value is a great idea for error handling (when `goto err`). It may set errno but we are not going to check it.

2023-06-14 11:48 UTC, RinHizakura commented on src/serial.c
> +    pthread_mutex_init(&priv->loopback_lock, NULL);
Do `pthread_mutex_destroy` when doing error handling and closing the serial device (`serail_exit`) will be a good practice.

2023-06-14 11:48 UTC, RinHizakura commented on src/serial.c
> +            serial_receive(s);
I don't think that you fallthrough the case intentionally. Add `break` for each case.

2023-06-14 14:21 UTC, RinHizakura commented on src/serial.c
>      .msr = UART_MSR_DCD | UART_MSR_DSR | UART_MSR_CTS,
Change this to `DEFAULT_MSR`

2023-06-16 07:20 UTC, yanjiew1 commented
Hello, I have a another solution to solve the problem of signal input. This solution is not based on epoll and eventfd.

Instead of using signal to notify the main thread to read from stdin, just perform the read in the worker thread. Use mutex lock to protect the serial device's internal structure and use conditional variable, so that the main thread can notify the worker thread that it should read more bytes from stdin.

Please see this commit. Instead of changing a lot of codes to not only solve the problem but also add new features, I try to make minimal changes to the code to solve the problem of serial input.
https://github.com/yanjiew1/kvm-host/commit/18f24387002b7833bf031f622da27cbcd127cfb0

2023-06-17 03:09 UTC, jserv commented
> Please see this commit. Instead of changing a lot of codes to not only solve the problem but also add new features, I try to make minimal changes to the code to solve the problem of serial input. [yanjiew1@edb3aa4](https://github.com/yanjiew1/kvm-host/commit/edb3aa4c98a0e1a94e0421f04dcf674284f8c5db)

@RinHizakura, what do you think of the above approach?

2023-06-17 03:28 UTC, RinHizakura commented
This one looks better for me! In my opinion, it would be great to keep kvm-host as simple as possible(but still complete and efficient) as it is a "minimalist hypervisor".

2023-06-17 04:02 UTC, jserv commented
> This one looks better for me! In my opinion, it would be great to keep kvm-host as simple as possible(but still complete and efficient) as it is a "minimalist hypervisor".

Agree.
@yanjiew1, Please rebase and rework the handling of multi-threaded FIFO operations properly.

2023-06-17 09:46 UTC, closed without merging