Port to arm64 architecture
sysprog21/kvm-host pull request #17
Opened 2023-06-15 14:20 UTC by yanjiew1

I successfully ported the kvm-host to arm64. These are what I modified:
- Separate architecture specific codes from architecture-neutral codes
- Import libfdt source code for arm64. (the license is compatible)
- Use dynamic IRQ number assignment rather than hard-coded IRQ number in virtio-blk and serial device
- Not registering PCI bus to io_bus and mmio_bus.  Leave this work for architecture specific initialization routine
- Fix serial input bug by reading from stdin in worker thread. Use a mutex lock and a conditional variable for synchronization
- The error reporting routine `throw_err` can support printf style formatting.

2023-06-15 16:14 UTC, jserv requested changes
Instead of submitting a series of patches, let's work on decoupling x86-64 specific code out of the generic part first.

2023-06-16 08:01 UTC, yanjiew1 commented
I have force pushed a new version that only contains the changes that separate x86-64 specific code out of generic implementation.

The original code is moved to another branch for backup.
https://github.com/yanjiew1/kvm-host/tree/arm64-final

2023-06-16 08:36 UTC, jserv commented on src/arch/x86/vm-arch.h
> +#pragma once
Rename this file to `src/arch/x86/desc.h` which stands for the architecture-specific descriptions.

2023-06-16 10:56 UTC, jserv commented on src/arch/x86/vm.c
> +#error "This virtual machine requires Linux/x86_64."
Refine the error message as following:
> This implementation is dedicated to Linux/x86-64.

2023-06-16 10:57 UTC, jserv commented on src/arch/x86/vm.c
> +
Remove this blank line.

2023-06-16 10:59 UTC, jserv commented on Makefile
> +	OBJS += arch/x86/vm.o
Append
```c
CFLAGS += -include src/arch/x86/desc.h
```

2023-06-16 11:00 UTC, jserv commented on src/vm.h
> +#include "vm-arch.h"
Remove this inclusion since we don't want to expose the implementation details.

2023-06-17 03:07 UTC, merged

2023-06-17 03:07 UTC, jserv commented
Thank @yanjiew1 for contributing. Let's move forward to Arm64 specific commits.